---
apiVersion: v1
kind: ConfigMap

metadata:
  name: cloudcart-config

  namespace: cloudcart

data:
  DB_HOST: postgres
  DB_PORT: "5432"

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  AWS_REGION: us-east-1

  SQS_QUEUE_URL: >-
     https://sqs.us-east-1.amazonaws.com/893511047266/cloudcart-user-registered-queue
